# Generated by Django 4.1.7 on 2023-04-21 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_webpage_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='webpage',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.gender'),
        ),
    ]
